version: '3.8'
services:
  web:
    build: ./mysite
    container_name: otrpo-pokemoon
    command: sh -c "python manage.py migrate && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - db-conn
      - redis-conn
  db:
    image: postgres:latest
    container_name: otrpo-db
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-conn
  redis:
    image: redis:7.0.9-alpine
    container_name: otrpo-redis
    restart: unless-stopped
    command: redis-server --port "${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - redis-conn

volumes:
  db-data:
  redis-data:

networks:
  db-conn:
    driver: bridge
  redis-conn:
    driver: bridge